### ISSUE TITLE
Red foreground for kitty

### ISSUE THREAD

**Issue by pmatos** [Bean6754/home#1]
Hi,

I was looking to theme my kitty with the nord theme and I found your config. However, I was quite surprised and blinded by the fact that you made the foreground red:

https://github.com/Bean6754/home/blob/4bdd916cafd15eae622c2d0a0892cc178e5a250c/.config/kitty/kitty.conf#L17

What was the reason for this? The nord theme is quite low contrast and this setting seems to deviate from the nord theme.

**Comment by Bean6754** [comment]
No reason, but I do need to change it soon.
![image](https://user-images.githubusercontent.com/9881825/42593901-9255e1ea-8545-11e8-9ce2-38027300772e.png)

Maybe #aa0000 will do nicely?

**Comment by Bean6754** [comment]
No reason, but I do need to change it soon.

Maybe #aa0000 will do nicely?

**Comment by pmatos** [comment]
Changed this to:
```
foreground            #d8dee8
background            #2f343f
```
